version: '3'
services:
  detection-1:
    image: docker.io/shixiongqi/kn-dummy
    container_name: detection-1
    environment:
      - SLEEP_TIME=453000

  search-2:
    image: docker.io/shixiongqi/kn-dummy
    container_name: search-2
    environment:
      - SLEEP_TIME=20000

  index-3:
    image: docker.io/shixiongqi/kn-dummy
    container_name: index-3
    environment:
      - SLEEP_TIME=1000

  charging-4:
    image: docker.io/shixiongqi/kn-dummy
    container_name: charging-4
    environment:
      - SLEEP_TIME=50000

  persist-5:
    image: docker.io/shixiongqi/kn-dummy
    container_name:  persist-5
    environment:
      - SLEEP_TIME=10000
  
  parking-proxy:
    image: firesh/nginx-lua
    ports:
      - "80:80"
    command: ["/bin/sh", "-c", "apk add --no-cache curl && nginx -g 'daemon off;'"]